# Generated by Django 6.0.6 on 2026-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('bakery', 'Bakery'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('household', 'Household'), ('skincare', 'Skincare'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
